services:
  pgadmin:
    container_name: carRental_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-loc@wp.pl}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - "${PGADMIN_PORT:-5555}:80"

  postgres:
    container_name: carRental
    image: postgres
    ports:
      - "5435:5432"

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carRental